import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
  TextInput,
  Alert,
  ActivityIndicator,
  StatusBar,
} from "react-native";
import { MaterialCommunityIcons, Ionicons } from "@expo/vector-icons";
import axios from "axios";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import BASE_URL from "../config/api";

const COLORS = {
  primary: "#E60000",
  secondary: "#0B5E3C",
  dark: "#121212",
  white: "#FFFFFF",
  light: "#F8FAFC",
  muted: "#64748B",
  border: "#E2E8F0",
  softRed: "#FFF1F1",
  softGreen: "#EAF7F1",
};

const API_ENDPOINTS = {
  verifyIdentity: "",
};

const VerificationScreen = ({ navigation }) => {
  const [view, setView] = useState("list");
  const [selectedTask, setSelectedTask] = useState(null);
  const [loading, setLoading] = useState(false);
  const [isAdmin, setIsAdmin] = useState(false);

  const [prices, setPrices] = useState({
    bvn_full: 500,
    bvn_basic: 200,
    face_id: 800,
    phone_verify: 300,
  });

  const [formData, setFormData] = useState({
    searchValue: "",
    pin: "",
  });

  const [verificationResult, setVerificationResult] = useState(null);
  const [newPrice, setNewPrice] = useState("");

  const services = [
    {
      id: "phone_verify",
      title: "Phone Number Verification",
      icon: "phone-check",
      inputLabel: "Phone Number",
      maxLength: 11,
    },
    {
      id: "bvn_basic",
      title: "BVN Basic Search",
      icon: "bank-outline",
      inputLabel: "BVN Number",
      maxLength: 11,
    },
    {
      id: "bvn_full",
      title: "Full BVN Details",
      icon: "bank-check",
      inputLabel: "BVN Number",
      maxLength: 11,
    },
    {
      id: "face_id",
      title: "Face ID Recognition",
      icon: "face-recognition",
      inputLabel: "Enrollment ID",
      maxLength: 15,
    },
  ];

  useEffect(() => {
    const checkRole = async () => {
      const storedUser = await AsyncStorage.getItem("userData");

      if (storedUser) {
        const parsed = JSON.parse(storedUser);
        setIsAdmin(parsed?.role === "admin");
      }
    };

    checkRole();
  }, []);

  const handleUpdatePrice = async (serviceId) => {
    if (!newPrice.trim()) {
      Alert.alert("Error", "Enter price");
      return;
    }

    setPrices({
      ...prices,
      [serviceId]: parseInt(newPrice, 10),
    });

    setNewPrice("");

    Alert.alert("Bellaj Data Hub", "Price updated locally for this session.");
  };

  const handleVerify = async () => {
    if (!formData.searchValue.trim() || !formData.pin.trim()) {
      Alert.alert("Error", "Fill all fields");
      return;
    }

    if (!API_ENDPOINTS.verifyIdentity) {
      Alert.alert("Not Configured", "Verification API is not configured.");
      return;
    }

    setLoading(true);

    try {
      const token = await AsyncStorage.getItem("userToken");

      const res = await axios.post(
        API_ENDPOINTS.verifyIdentity,
        {
          type: selectedTask.id,
          value: formData.searchValue.trim(),
          pin: formData.pin,
          charge: prices[selectedTask.id],
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
      );

      if (res.data.success) {
        setVerificationResult(res.data.data);
        setView("result");
      }
    } catch (err) {
      Alert.alert(
        "Failed",
        err.response?.data?.message || "Verification Error",
      );
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = async (data) => {
    const html = `
      <html>
        <body style="padding: 50px; font-family: sans-serif;">
          <h1 style="text-align: center; color: #E60000;">
            BELLAJ DATA HUB VERIFICATION SLIP
          </h1>
          <hr/>
          <p><b>Service:</b> ${selectedTask?.title || "Verification"}</p>
          <p><b>Name:</b> ${data?.firstName || ""} ${data?.lastName || ""}</p>
          <p><b>ID Used:</b> ${formData.searchValue}</p>
          <p><b>Date:</b> ${new Date().toDateString()}</p>

          <div style="margin-top: 50px; border: 1px solid #0B5E3C; padding: 20px;">
            <p>Verification Status: <b style="color:#0B5E3C;">VERIFIED</b></p>
          </div>

          <p style="margin-top: 40px; font-size: 12px; color: #64748B;">
            Generated by Bellaj Data Hub
          </p>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri);
  };

  if (view === "list") {
    return (
      <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
        <StatusBar barStyle="dark-content" backgroundColor={COLORS.white} />

        <Text style={styles.header}>Identity Verification</Text>
        <Text style={styles.subHeader}>
          Bellaj Data Hub verification services
        </Text>

        {services.map((s) => (
          <View key={s.id} style={styles.serviceWrapper}>
            <TouchableOpacity
              style={styles.card}
              activeOpacity={0.85}
              onPress={() => {
                setSelectedTask(s);
                setFormData({ searchValue: "", pin: "" });
                setVerificationResult(null);
                setView("form");
              }}
            >
              <View style={styles.iconCircle}>
                <MaterialCommunityIcons
                  name={s.icon}
                  size={28}
                  color={COLORS.primary}
                />
              </View>

              <View style={styles.cardContent}>
                <Text style={styles.cardTitle}>{s.title}</Text>
                <Text style={styles.cardPrice}>Fee: ₦{prices[s.id]}</Text>
              </View>

              <Ionicons name="chevron-forward" size={20} color="#CBD5E1" />
            </TouchableOpacity>

            {isAdmin && (
              <View style={styles.adminRow}>
                <TextInput
                  style={styles.adminInput}
                  placeholder="New Price"
                  placeholderTextColor="#94A3B8"
                  keyboardType="numeric"
                  value={newPrice}
                  onChangeText={setNewPrice}
                />

                <TouchableOpacity
                  style={styles.updateBtn}
                  onPress={() => handleUpdatePrice(s.id)}
                >
                  <Text style={styles.updateBtnText}>SET</Text>
                </TouchableOpacity>
              </View>
            )}
          </View>
        ))}
      </ScrollView>
    );
  }

  if (view === "form") {
    return (
      <View style={styles.container}>
        <TouchableOpacity
          onPress={() => setView("list")}
          style={styles.backLink}
        >
          <Ionicons name="arrow-back" size={24} color={COLORS.primary} />
          <Text style={styles.backLinkText}>Back</Text>
        </TouchableOpacity>

        <Text style={styles.formTitle}>{selectedTask?.title}</Text>

        <Text style={styles.formPrice}>
          Service Charge: ₦{prices[selectedTask?.id]}
        </Text>

        <View style={styles.inputBox}>
          <Text style={styles.inputLabel}>{selectedTask?.inputLabel}</Text>

          <TextInput
            style={styles.input}
            placeholder={`Enter ${selectedTask?.inputLabel}`}
            placeholderTextColor="#94A3B8"
            keyboardType="numeric"
            maxLength={selectedTask?.maxLength}
            value={formData.searchValue}
            onChangeText={(v) =>
              setFormData({
                ...formData,
                searchValue: v,
              })
            }
          />
        </View>

        <View style={styles.inputBox}>
          <Text style={styles.inputLabel}>Transaction PIN</Text>

          <TextInput
            style={styles.input}
            placeholder="****"
            placeholderTextColor="#94A3B8"
            secureTextEntry
            keyboardType="numeric"
            maxLength={4}
            value={formData.pin}
            onChangeText={(v) =>
              setFormData({
                ...formData,
                pin: v,
              })
            }
          />
        </View>

        <TouchableOpacity
          style={[styles.mainBtn, loading && { opacity: 0.7 }]}
          onPress={handleVerify}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color={COLORS.white} />
          ) : (
            <Text style={styles.mainBtnText}>VERIFY IDENTITY</Text>
          )}
        </TouchableOpacity>
      </View>
    );
  }

  if (view === "result") {
    return (
      <View style={styles.container}>
        <View style={styles.successCard}>
          <Ionicons
            name="checkmark-circle"
            size={80}
            color={COLORS.secondary}
          />

          <Text style={styles.successTitle}>Verification Successful</Text>

          <View style={styles.resData}>
            <Text style={styles.resLabel}>Name</Text>
            <Text style={styles.resValue}>
              {verificationResult?.firstName || ""}{" "}
              {verificationResult?.lastName || ""}
            </Text>

            <Text style={styles.resLabel}>Reference</Text>
            <Text style={styles.resValue}>
              {Math.random().toString(36).substring(7).toUpperCase()}
            </Text>
          </View>

          <TouchableOpacity
            style={styles.pdfBtn}
            onPress={() => generatePDF(verificationResult)}
          >
            <MaterialCommunityIcons
              name="file-pdf-box"
              size={24}
              color={COLORS.white}
            />
            <Text style={styles.pdfBtnText}>DOWNLOAD SLIP</Text>
          </TouchableOpacity>

          <TouchableOpacity
            onPress={() => setView("list")}
            style={styles.closeBtn}
          >
            <Text style={styles.closeBtnText}>Done</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  return null;
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    padding: 20,
  },
  header: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.primary,
    marginTop: 40,
  },
  subHeader: {
    color: COLORS.secondary,
    fontSize: 14,
    marginBottom: 30,
    marginTop: 4,
  },
  serviceWrapper: {
    marginBottom: 15,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.light,
    padding: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
  },
  iconCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.softRed,
    justifyContent: "center",
    alignItems: "center",
  },
  cardContent: {
    flex: 1,
    marginLeft: 15,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  cardPrice: {
    fontSize: 13,
    color: COLORS.secondary,
    fontWeight: "700",
    marginTop: 2,
  },
  adminRow: {
    flexDirection: "row",
    marginTop: 8,
    paddingHorizontal: 10,
  },
  adminInput: {
    flex: 1,
    height: 38,
    backgroundColor: COLORS.light,
    borderRadius: 6,
    paddingHorizontal: 10,
    fontSize: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    color: COLORS.dark,
  },
  updateBtn: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 15,
    marginLeft: 10,
    borderRadius: 6,
    justifyContent: "center",
  },
  updateBtnText: {
    color: COLORS.white,
    fontSize: 10,
    fontWeight: "bold",
  },
  backLink: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 40,
    marginBottom: 20,
  },
  backLinkText: {
    marginLeft: 8,
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: "600",
  },
  formTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  formPrice: {
    fontSize: 16,
    color: COLORS.secondary,
    marginTop: 5,
    marginBottom: 30,
    fontWeight: "600",
  },
  inputBox: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    color: COLORS.muted,
    marginBottom: 8,
    fontWeight: "600",
  },
  input: {
    backgroundColor: COLORS.light,
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    fontSize: 16,
    color: COLORS.dark,
  },
  mainBtn: {
    backgroundColor: COLORS.primary,
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
  },
  mainBtnText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold",
  },
  successCard: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  successTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.secondary,
    marginTop: 20,
  },
  resData: {
    width: "100%",
    backgroundColor: COLORS.light,
    padding: 20,
    borderRadius: 15,
    marginTop: 30,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.secondary,
  },
  resLabel: {
    fontSize: 12,
    color: COLORS.muted,
  },
  resValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.dark,
    marginBottom: 15,
  },
  pdfBtn: {
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    padding: 18,
    borderRadius: 12,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
  },
  pdfBtnText: {
    color: COLORS.white,
    fontWeight: "bold",
    marginLeft: 10,
  },
  closeBtn: {
    marginTop: 25,
  },
  closeBtnText: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
  },
});

export default VerificationScreen;
